name: Update GitHub Streak

on:
  schedule:
    - cron: "0 3 * * *"

  push:
    paths:
      - ".github/workflows/streak-stats.yml"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Streak
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=tokyonight&background=1A1B27&border=E4E4E7&stroke=30363D&ring=70A5FD&fire=FFA500&currStreakNum=70A5FD&sideNums=70A5FD&currStreakLabel=70A5FD&sideLabels=70A5FD&dates=8B949E&hide_border=false&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated streak
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update GitHub streak" || exit 0
          git push
